- hosts: localhost
  become: true
  
  vars:    
    jenkins_hostname: 34.89.244.216
    java_packages:
      - openjdk-8-jdk
  
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins

